# Default values for ehh-fe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
configHash: "1" # configuration change detection
appName: ehh-fe
version: ${project.version}
domainName: stxcn.codenow.com
buildNumber: "${env.BUILD_NUMBER}"

image:
  repository: codenow-stxcn-docker.jfrog.io/codenow/ehh-fe
  tag:  ${project.version}
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

fluentbit:
  istioProxy:
    enabled: true
    parser: envoy-logging-filter-parser
  parser: oxus-app-component-json

configFiles: {}
environmentVariables: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
